lstm: ../src/main.c ../src/layer/lstm.c ../src/layer/affine.c ../src/function/sigmoid.c ../src/function/relu.c
	gcc -o lstm ../src/main.c ../src/layer/lstm.c ../src/layer/affine.c ../src/function/sigmoid.c ../src/function/relu.c
